### ISSUE TITLE
GCC Tenant Support (https://graph.microsoft.us) MS Graph API

### ISSUE THREAD

**Issue by spjeff** [waldekmastykarz/mgt-spfx#2]
Hey @waldekmastykarz 

Awesome work on MGT components.   Work great with clean user friendly display.

How can we add support for GCC Tenant calling https://graph.microsoft.us MS Graph API domain endpoint?

Thank you.  Keep up great work.

**Comment by waldekmastykarz** [comment]
All the credit goes to the MGT team and the community. Support for GCC would be a perfect question to ask in the MGT repo @ https://github.com/microsoftgraph/microsoft-graph-toolkit.
